# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2 #Added
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage #Added
from PyQt5.QtGui import QPixmap #Added
from PyQt5.QtCore import pyqtSlot

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.imgLabel = QtWidgets.QLabel(MainWindow)
        self.imgLabel.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.imgLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel.setLineWidth(3)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")


        self.overlayLabel = QtWidgets.QLabel(MainWindow)
        self.overlayLabel.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.overlayLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.overlayLabel.setLineWidth(3)
        self.overlayLabel.setText("")
        self.overlayLabel.setObjectName("overlayLabel")

        self.centerLabel = QtWidgets.QLabel(MainWindow)
        self.centerLabel.setGeometry(QtCore.QRect(822, 105, 122, 160))
        self.centerLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.centerLabel.setText("")
        self.centerLabel.setObjectName("centerLabel")



        self.front_1a_Label = QtWidgets.QLabel(MainWindow)
        self.front_1a_Label.setGeometry(QtCore.QRect(819, 93, 44, 32))
        self.front_1a_Label.setText("")
        self.front_1a_Label.setObjectName("front_1a_Label")

        self.front_1b_Label = QtWidgets.QLabel(MainWindow)
        self.front_1b_Label.setGeometry(QtCore.QRect(804, 72, 55, 43))
        self.front_1b_Label.setText("")
        self.front_1b_Label.setObjectName("front_1b_Label")

        self.front_1c_Label = QtWidgets.QLabel(MainWindow)
        self.front_1c_Label.setGeometry(QtCore.QRect(789, 51, 65, 48))
        self.front_1c_Label.setText("")
        self.front_1c_Label.setObjectName("front_1c_Label")

        self.front_1d_Label = QtWidgets.QLabel(MainWindow)
        self.front_1d_Label.setGeometry(QtCore.QRect(774, 30, 74, 54))
        self.front_1d_Label.setText("")
        self.front_1d_Label.setObjectName("front_1d_Label")

        self.front_2a_Label = QtWidgets.QLabel(MainWindow)
        self.front_2a_Label.setGeometry(QtCore.QRect(860, 89, 46, 16))
        self.front_2a_Label.setText("")
        self.front_2a_Label.setObjectName("front_2a_Label")

        self.front_2b_Label = QtWidgets.QLabel(MainWindow)
        self.front_2b_Label.setGeometry(QtCore.QRect(855, 68, 56, 23))
        self.front_2b_Label.setText("")
        self.front_2b_Label.setObjectName("front_2b_Label")

        self.front_2c_Label = QtWidgets.QLabel(MainWindow)
        self.front_2c_Label.setGeometry(QtCore.QRect(849, 46, 67, 24))
        self.front_2c_Label.setText("")
        self.front_2c_Label.setObjectName("front_2c_Label")

        self.front_2d_Label = QtWidgets.QLabel(MainWindow)
        self.front_2d_Label.setGeometry(QtCore.QRect(844, 25, 78, 24))
        self.front_2d_Label.setText("")
        self.front_2d_Label.setObjectName("front_2d_Label")

        self.front_3a_Label = QtWidgets.QLabel(MainWindow)
        self.front_3a_Label.setGeometry(QtCore.QRect(903, 92, 44, 32))
        self.front_3a_Label.setText("")
        self.front_3a_Label.setObjectName("front_3a_Label")

        self.front_3b_Label = QtWidgets.QLabel(MainWindow)
        self.front_3b_Label.setGeometry(QtCore.QRect(907, 72, 55, 43))
        self.front_3b_Label.setText("")
        self.front_3b_Label.setObjectName("front_3b_Label")

        self.front_3c_Label = QtWidgets.QLabel(MainWindow)
        self.front_3c_Label.setGeometry(QtCore.QRect(912, 51, 65, 48))
        self.front_3c_Label.setText("")
        self.front_3c_Label.setObjectName("front_3c_Label")

        self.front_3d_Label = QtWidgets.QLabel(MainWindow)
        self.front_3d_Label.setGeometry(QtCore.QRect(918, 30, 74, 54))
        self.front_3d_Label.setText("")
        self.front_3d_Label.setObjectName("front_3d_Label")

        self.SHOW = QtWidgets.QPushButton(MainWindow)
        self.SHOW.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.SHOW.setObjectName("SHOW")

        #Load graphics
        self.overlay = QPixmap("graphics/parking_overlay.png")

        self.center = QPixmap("graphics/go_kart_center.png")


        self.front_1a_ON = QPixmap("graphics/front_1a_ON.png")
        self.front_1b_ON = QPixmap("graphics/front_1b_ON.png")
        self.front_1c_ON = QPixmap("graphics/front_1c_ON.png")
        self.front_1d_ON = QPixmap("graphics/front_1d_ON.png")

        self.front_1a_OFF = QPixmap("graphics/front_1a_OFF.png")
        self.front_1b_OFF = QPixmap("graphics/front_1b_OFF.png")
        self.front_1c_OFF = QPixmap("graphics/front_1c_OFF.png")
        self.front_1d_OFF = QPixmap("graphics/front_1d_OFF.png")

        self.front_2a_ON = QPixmap("graphics/front_2a_ON.png")
        self.front_2b_ON = QPixmap("graphics/front_2b_ON.png")
        self.front_2c_ON = QPixmap("graphics/front_2c_ON.png")
        self.front_2d_ON = QPixmap("graphics/front_2d_ON.png")

        self.front_2a_OFF = QPixmap("graphics/front_2a_OFF.png")
        self.front_2b_OFF = QPixmap("graphics/front_2b_OFF.png")
        self.front_2c_OFF = QPixmap("graphics/front_2c_OFF.png")
        self.front_2d_OFF = QPixmap("graphics/front_2d_OFF.png")

        self.front_3a_ON = QPixmap("graphics/front_3a_ON.png")
        self.front_3b_ON = QPixmap("graphics/front_3b_ON.png")
        self.front_3c_ON = QPixmap("graphics/front_3c_ON.png")
        self.front_3d_ON = QPixmap("graphics/front_3d_ON.png")

        self.front_3a_OFF = QPixmap("graphics/front_3a_OFF.png")
        self.front_3b_OFF = QPixmap("graphics/front_3b_OFF.png")
        self.front_3c_OFF = QPixmap("graphics/front_3c_OFF.png")
        self.front_3d_OFF = QPixmap("graphics/front_3d_OFF.png")



        ####Added
        self.SHOW.clicked.connect(self.onClicked)
        ####Added

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)







    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SHOW.setText(_translate("MainWindow", "Show"))

    #Added
    def onClicked(self):
        print("here")
        cap = cv2.VideoCapture(0,cv2.CAP_DSHOW)
        cap.set(3, 1024)
        cap.set(4, 600)

        while cap.isOpened():
            ret, frame = cap.read()
            if ret == True:
                self.displayImage(frame, 1)
                cv2.waitKey()
            else:
                print("Return not found")
        cap.release()
        cv2.destroyAllWindows()
        print("Exited while loop")

    def displayImage(self, img, window=1):
        #overlay_img = Image.open("./parking_overlay.png")
        qformat = QImage.Format_Indexed8
        qformat = QImage.Format_Indexed8


        if len(img.shape) == 3:
            if (img.shape[2]) == 4:
                qformat = QImage.Format_RGBA888
            else:
                qformat = QImage.Format_RGB888
            img = QImage(img, img.shape[1], img.shape[0], qformat)
            img = img.rgbSwapped()


            self.imgLabel.setPixmap(QPixmap.fromImage(img))
            self.overlayLabel.setPixmap(self.overlay)
            self.centerLabel.setPixmap(self.center)
            self.front_1a_Label.setPixmap(self.front_1a_OFF)
            self.front_1b_Label.setPixmap(self.front_1b_OFF)
            self.front_1c_Label.setPixmap(self.front_1c_OFF)
            self.front_1d_Label.setPixmap(self.front_1d_OFF)

            self.front_2a_Label.setPixmap(self.front_2a_OFF)
            self.front_2b_Label.setPixmap(self.front_2b_OFF)
            self.front_2c_Label.setPixmap(self.front_2c_OFF)
            self.front_2d_Label.setPixmap(self.front_2d_OFF)

            self.front_3a_Label.setPixmap(self.front_3a_OFF)
            self.front_3b_Label.setPixmap(self.front_3b_OFF)
            self.front_3c_Label.setPixmap(self.front_3c_OFF)
            self.front_3d_Label.setPixmap(self.front_3d_OFF)


            self.imgLabel.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
            self.overlayLabel.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)

    #Added


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
